AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5.1
  Exclude:
    - db/schema.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25 # Consider reducing the value to 20

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*_spec.rb
    - lib/tasks/**/*.rake
    - config/**/*.rb

Metrics/ClassLength:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/IndentHash:
  EnforcedStyle: consistent
